# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0002_auto_20161102_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='img_ambiance',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='journey',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
