# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0006_auto_20161103_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_journey', to='snapventure.Profile'),
        ),
    ]
