# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0007_auto_20161103_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='order_id',
        ),
        migrations.AddField(
            model_name='step',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edges',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_node', to='snapventure.Step'),
        ),
        migrations.AddField(
            model_name='edges',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='snapventure.Step'),
        ),
        migrations.AddField(
            model_name='step',
            name='neighbors',
            field=models.ManyToManyField(through='snapventure.Edges', to='snapventure.Step'),
        ),
    ]
