# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0008_auto_20161109_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edges',
            new_name='Edge',
        ),
    ]
