# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0009_auto_20161109_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='name',
        ),
        migrations.AddField(
            model_name='edge',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edge',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
