# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0010_auto_20161109_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=3, max_digits=3)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scan',
            name='name',
        ),
        migrations.AddField(
            model_name='scan',
            name='profile',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='snapventure.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='state',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='snapventure.State'),
            preserve_default=False,
        ),
    ]
