# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0013_auto_20161110_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
