# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0015_auto_20161110_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='neighbors',
            new_name='neighbours',
        ),
    ]
