# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0016_auto_20161116_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='img_description',
            field=models.ImageField(blank=True, default='snapventure/uploads/img/default/journey-placeholder.png', upload_to='sapventure/uploads/img/journey_description'),
        ),
    ]
