# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0021_step_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journey',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
