# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 08:36
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snapventure', '0022_auto_20161222_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
